Repository openshift/node-feature-discovery, pull requests merged in 2020-10, with the labels that each got.

#16 Bug 1878163: Updating node-feature-discovery builder & base images to be consistent with ART
  Dockerfile
Labels: bugzilla/severity-high, bugzilla/valid-bug

#19 Fix component information missing in OWNERS file
  OWNERS
Labels: approved, lgtm

#20 Fix pathPrefix in source/config.go
  Dockerfile
  Makefile
Labels: approved, lgtm, priority/critical-urgent

#17 Add label RHEL_VERSION
  source/system/system.go
Labels: approved, lgtm

#18 Updating node-feature-discovery builder & base images to be consistent with ART
  Dockerfile
Labels: approved, lgtm

#22 fix gobuild ldflag on Makefile
  Makefile
Labels: approved, lgtm
